### ISSUE TITLE
Secret required in server.xml for AJP-connector 

### ISSUE THREAD

**Issue by OyvindLGjesdal** [robertdebock/ansible-role-service#2]
## Describe the bug

Tomcat systemd service refuses to start, due to mandatory secret missing from server.xml (template.)

This was introduced in; Tomcat 7.0.100, Tomcat 8.5.59, and tomcat 9.0.31, according to the logs, which is less than the default version for tomcat 7 and 9 values.

From the changelog:
```
Rename the requiredSecret attribute of the AJP/1.3 Connector to secret and add a new attribute secretRequired that defaults to true. When secretRequired is true the AJP/1.3 Connector will not start unless the secret attribute is configured to a non-null, non-zero length String. (markt)
````

I don't know what would be the best way to solve in the server.yml template. Having a `instance.ajp_secret` variable on the ajp Connector element, with a default secret generated, or should the default requiredSecret attribute be set to false? 

I added a secret attribute manually on the box, and the service then started.

--

## Playbook

```yaml
---
...
 tasks:
  - import_role:
      name: "ansible-role-tomcat"
    vars:
      tomcat_instances:
      - name: "tomcat-version-9"
        version: 9
    become: true
```

## Output
```
Oct 19 19:36:11 example.org catalina.sh[34248]:                 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Oct 19 19:36:11 example.org catalina.sh[34248]:                 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Oct 19 19:36:11 example.org catalina.sh[34248]:                 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Oct 19 19:36:11 example.org catalina.sh[34248]:                 at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
Oct 19 19:36:11 example.org catalina.sh[34248]:                 at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
Oct 19 19:36:11 example.org catalina.sh[34248]:         Caused by: java.lang.IllegalArgumentException: The AJP Connector is configured with secretRequired="true" but the secret attribute is either null or "". This combination is not valid.
Oct 19 19:36:11 example.org catalina.sh[34248]:                 at org.apache.coyote.ajp.AbstractAjpProtocol.start(AbstractAjpProtocol.java:270)
Oct 19 19:36:11 example.org catalina.sh[34248]:                 at org.apache.catalina.connector.Connector.startInternal(Connector.java:1064)
Oct 19 19:36:11 example.org catalina.sh[34248]:                 ... 12 more
```
## Environment

- Control node OS: Fedora release 30 (Thirty)
- Control node Ansible version: 2.99
- Managed node OS:  Centos 8

**Comment by OyvindLGjesdal** [comment]
I posted this in the wrong repo, closing and opening a new issue under ansible-role-tomcat.
