### ISSUE TITLE
Add a SyslogIdentifier section in .service

### ISSUE THREAD

**Issue by CedricLevasseur** [robertdebock/ansible-role-service#4]
## Proposed feature

Adding a syslog identifier make the journal clearable and filterable

## Rationale

It's actually unclear. For example, i'm using tomcat, and it's hard to identify it in journalctl
```
Apr 27 05:36:02 myhost bash[88952]: java.io.FileNotFoundException: /somewhere/logs/localhost.2022-04-27.log (Permission denied)
Apr 27 05:36:02 myhost bash[88952]: at java.io.FileOutputStream.open0(Native Method)
Apr 27 05:36:02 myhost bash[88952]: at java.io.FileOutputStream.open(FileOutputStream.java:270)
Apr 27 05:36:02 myhost bash[88952]: at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
```

It would be clearer if it were :
`Apr 27 05:36:02 myhost tomcat: java.io.FileNotFoundException: /somewhere/logs/localhost.2022-04-27.log (Permission denied)`
And also i could use
`journalctl -t tomcat`

## Additional context
Here is the source of the tip for SyslogIdentifier in systemd:
https://stackoverflow.com/a/43830129/1654749

Thank you

**Comment by CedricLevasseur** [comment]
I'm working on a Pull Request
